// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwrWthsfUjfmF5GkoRsTv6M0MhYAUNXY',
    appId: '1:998158972085:web:0d3328d1ea8d76c929fafc',
    messagingSenderId: '998158972085',
    projectId: 'push-notification-724b0',
    authDomain: 'push-notification-724b0.firebaseapp.com',
    storageBucket: 'push-notification-724b0.appspot.com',
    measurementId: 'G-XCL9JM6HS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLw0WRWQG6A2ZDJDWpTpdACexWScj4B3c',
    appId: '1:998158972085:android:8080e0ecc7789bb629fafc',
    messagingSenderId: '998158972085',
    projectId: 'push-notification-724b0',
    storageBucket: 'push-notification-724b0.appspot.com',
  );

}